"""Data acquisition layer.

Two sources are supported:

1. Live NBA stats via `nba_api` (`fetch_real_season`) -- pulls team and player
   box-score/advanced splits straight from stats.nba.com. Use this when the
   pipeline runs somewhere with outbound access to stats.nba.com (it is
   frequently blocked from data-center IPs/proxies, so it is not assumed to
   be available).
2. A synthetic league generator (`generate_synthetic_league`) that produces
   a multi-season, multi-team, multi-player dataset with realistic
   correlations: a persistent player universe (so career injury history and
   playoff-performance deltas actually accumulate over time), era trends
   (rising 3-point rate a la "Era Ball"), roster continuity/turnover, and
   playoff outcomes generated by actually simulating brackets with
   `src.simulate`, so the labels are driven by the same skill/injury/
   playoff-delta/home-court signals the feature pipeline computes -- not
   random noise bolted on afterward.

`load_league`, at the bottom, tries the real source first per season and
falls back to synthetic generation, so the rest of the pipeline never has to
know which source produced a given season.
"""
from __future__ import annotations

import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from config import (
    DATA_RAW_DIR, EASTERN_CONFERENCE, END_SEASON_YEAR, MAX_MODELED_YEAR, PLAYERS_PER_TEAM,
    RANDOM_SEED, ROTATION_SIZE, START_SEASON_YEAR, TEAMS, WESTERN_CONFERENCE,
)
from src.era import era_big_man_weight, era_guard_weight, era_pace, era_three_rate
from src.simulate import simulate_series

POSITIONS = ["PG", "SG", "SF", "PF", "C"]


def season_label(year: int) -> str:
    """2024 -> '2023-24' (year = the season's ending calendar year)."""
    return f"{year - 1}-{str(year)[-2:]}"


# --------------------------------------------------------------------------
# 1. Real data via nba_api (best-effort; network dependent)
# --------------------------------------------------------------------------

def fetch_real_season(year: int, cache_dir: Path = DATA_RAW_DIR) -> dict[str, pd.DataFrame] | None:
    """Pull team + player advanced stats for one season from stats.nba.com.

    Returns None (and warns) on any network/API failure so callers can fall
    back to synthetic data without crashing the whole pipeline.
    """
    season = season_label(year)
    team_cache = cache_dir / f"real_team_{season}.parquet"
    player_cache = cache_dir / f"real_player_{season}.parquet"
    if team_cache.exists() and player_cache.exists():
        return {"team": pd.read_parquet(team_cache), "player": pd.read_parquet(player_cache)}

    try:
        from nba_api.stats.endpoints import leaguedashteamstats, leaguedashplayerstats
    except ImportError:
        warnings.warn("nba_api not installed; skipping real data fetch.")
        return None

    try:
        team_df = leaguedashteamstats.LeagueDashTeamStats(
            season=season, measure_type_detailed_defense="Advanced", timeout=15,
        ).get_data_frames()[0]
        time.sleep(0.6)  # be polite to the API
        player_df = leaguedashplayerstats.LeagueDashPlayerStats(
            season=season, measure_type_detailed_defense="Advanced", timeout=15,
        ).get_data_frames()[0]
    except Exception as exc:  # noqa: BLE001 - any failure means "use synthetic"
        warnings.warn(f"Live NBA API fetch failed for {season} ({exc!r}); will use synthetic data.")
        return None

    team_df.to_parquet(team_cache)
    player_df.to_parquet(player_cache)
    return {"team": team_df, "player": player_df}


# --------------------------------------------------------------------------
# 2. Synthetic league generator
# --------------------------------------------------------------------------

def _make_player_universe(n_players: int, seed: int) -> pd.DataFrame:
    """A fixed pool of players with persistent career-long latent traits.

    entry_year spans through MAX_MODELED_YEAR (a fixed global, independent of
    whatever start_year/end_year a particular generate_synthetic_league call
    requests) so rookies keep entering every "future" season too -- and so
    historical seasons don't shift depending on how far into the future a
    given call also asks for.
    """
    rng = np.random.default_rng(seed)
    entry_age = rng.integers(19, 23, n_players)
    entry_year = rng.integers(START_SEASON_YEAR - 10, MAX_MODELED_YEAR, n_players)
    career_length = np.clip(rng.gamma(shape=3.0, scale=2.5, size=n_players).astype(int) + 1, 1, 20)

    return pd.DataFrame({
        "player_id": np.arange(1, n_players + 1),
        "position": rng.choice(POSITIONS, n_players),
        "entry_age": entry_age,
        "entry_year": entry_year,
        "career_length": career_length,
        # Overall latent skill (BPM-like, roughly -5 to +8 for stars)
        "base_skill": rng.normal(0, 2.2, n_players),
        # 0-1, right-skewed: most players are durable, a tail is fragile
        "injury_proneness": rng.beta(2, 6, n_players),
        # Career-long tendency to rise/fall in the playoffs (z-score-ish)
        "playoff_delta_latent": rng.normal(0, 1.0, n_players),
        "three_pt_ability": rng.normal(0, 1.0, n_players),
        "peak_age": rng.normal(27, 2.0, n_players),
    })


def _assign_rosters(universe: pd.DataFrame, year: int, prior_rosters: dict[str, list[int]],
                     rng: np.random.Generator) -> tuple[dict[str, list[int]], pd.DataFrame]:
    """Assign active players to the 30 teams for one season.

    Retains a majority of each team's prior roster (weighted toward higher-
    skill players staying put), then drafts remaining slots from the free-
    agent pool so every team ends up with PLAYERS_PER_TEAM players. If the
    league-wide player pool ever runs short (e.g. a narrow date range is
    requested), replacement-level "10-day contract" fillers are fabricated
    on the spot so the pipeline never crashes; they carry no career history
    since they don't persist in the main player universe.
    """
    active = universe[(universe.entry_year <= year) &
                       (year < universe.entry_year + universe.career_length)]
    active_ids = set(active.player_id)
    skill = active.set_index("player_id")["base_skill"]

    rosters: dict[str, list[int]] = {}
    claimed: set[int] = set()

    for team in TEAMS:
        prior = [p for p in prior_rosters.get(team, []) if p in active_ids]
        if prior:
            keep_prob = 0.55 + 0.25 * (skill.reindex(prior).fillna(0).rank(pct=True))
            keep_mask = rng.random(len(prior)) < keep_prob.values
            retained = [p for p, keep in zip(prior, keep_mask) if keep]
        else:
            retained = []
        rosters[team] = retained
        claimed.update(retained)

    # Draft order for the free-agent fill-in below is reshuffled every season
    # (not the fixed TEAMS list order) -- looping teams in the same order
    # every year would let early-alphabet teams (ATL, BOS, BKN, ...) claim
    # the best available free agent first *every single season for 55
    # years straight*, baking in a permanent, alphabetical skill hierarchy
    # instead of the real league's year-to-year competitive churn.
    draft_order = list(rng.permutation(TEAMS))

    free_agents = sorted(active_ids - claimed, key=lambda pid: -skill.get(pid, -999))
    fa_idx = 0
    for team in draft_order:
        while len(rosters[team]) < PLAYERS_PER_TEAM and fa_idx < len(free_agents):
            rosters[team].append(free_agents[fa_idx])
            fa_idx += 1

    filler_rows = []
    next_id = int(universe.player_id.max()) + 1
    for team in draft_order:
        while len(rosters[team]) < PLAYERS_PER_TEAM:
            filler_rows.append({
                "player_id": next_id, "position": rng.choice(POSITIONS),
                "entry_age": 27, "entry_year": year, "career_length": 1,
                "base_skill": -1.6, "injury_proneness": 0.15,
                "playoff_delta_latent": 0.0, "three_pt_ability": 0.0, "peak_age": 27.0,
            })
            rosters[team].append(next_id)
            next_id += 1

    filler_df = pd.DataFrame(filler_rows, columns=universe.columns) if filler_rows else universe.iloc[0:0]
    return rosters, filler_df


def generate_synthetic_league(start_year: int = START_SEASON_YEAR, end_year: int = END_SEASON_YEAR,
                               seed: int = RANDOM_SEED) -> dict[str, pd.DataFrame]:
    """Generate a full synthetic league: player-seasons, team-seasons, and
    playoff results, for every season in [start_year, end_year] inclusive.
    """
    rng = np.random.default_rng(seed)
    universe = _make_player_universe(n_players=int(PLAYERS_PER_TEAM * 30 * 13), seed=seed)

    player_season_rows = []
    team_season_rows = []
    playoff_result_rows = []
    prior_rosters: dict[str, list[int]] = {}

    for year in sorted(range(start_year, end_year + 1)):
        season = season_label(year)
        three_rate_league = era_three_rate(year)
        big_wt, guard_wt = era_big_man_weight(year), era_guard_weight(year)
        rosters, filler_df = _assign_rosters(universe, year, prior_rosters, rng)
        prior_rosters = rosters
        season_pool = pd.concat([universe, filler_df], ignore_index=True) if len(filler_df) else universe

        team_skill = {}
        team_rows_this_year = {}
        for team in TEAMS:
            roster_ids = rosters[team]
            roster = season_pool[season_pool.player_id.isin(roster_ids)].copy()
            age = year - roster.entry_year + roster.entry_age
            roster = roster.assign(age=age)

            # Minutes/role: rank by (skill, age-curve-adjusted, era-position-value-
            # adjusted) within team. Wings (SF) sit at the neutral midpoint between
            # the big-man/guard eras; only true bigs and true guards swing with era.
            age_factor = 1 - 0.012 * (roster.age - roster.peak_age).abs()
            position_mult = roster.position.map({"PG": guard_wt, "SG": guard_wt, "SF": 1.0,
                                                   "PF": big_wt, "C": big_wt})
            effective_rating = roster.base_skill * age_factor.clip(lower=0.4) * position_mult
            order = effective_rating.sort_values(ascending=False).index
            n = len(roster)
            minutes = np.interp(np.arange(n), [0, ROTATION_SIZE - 1, n - 1], [34, 18, 8])
            roster.loc[order, "minutes_per_game"] = minutes[:n]

            # Injuries: games missed driven by persistent proneness + age.
            age_injury_bump = np.clip((roster.age - 30) * 0.015, 0, 0.35)
            miss_rate = np.clip(roster.injury_proneness + age_injury_bump, 0.01, 0.85)
            games_missed = rng.binomial(82, miss_rate)
            roster["games_played"] = 82 - games_missed
            roster["games_missed"] = games_missed

            # Shooting/production, correlated with skill & position & era 3PT trend.
            # Bigs' reluctance to shoot 3s scales with how big-man-favorable the
            # era is: 1980s post-up bigs almost never shot from deep; modern
            # "stretch" bigs shoot far more like guards.
            is_big = roster.position.isin(["PF", "C"])
            big_three_penalty = 0.14 * (big_wt - 0.5)
            three_att_rate = np.clip(
                three_rate_league + 0.15 * roster.three_pt_ability / 2.2 - big_three_penalty * is_big,
                0.01, 0.65,
            )
            fg_pct = np.clip(0.44 + 0.015 * roster.base_skill / 2.2 - 0.05 * three_att_rate, 0.36, 0.62)
            three_pct = np.clip(0.34 + 0.05 * roster.three_pt_ability, 0.20, 0.46)
            ft_pct = np.clip(0.75 + 0.03 * roster.base_skill / 2.2 + rng.normal(0, 0.05, n), 0.55, 0.93)

            # Rebounding/rim-protection bonus for bigs, and the assist bonus for
            # guards, both scale with how favorable the era is to that role: post
            # touches and boxing out were bigger boards sources in the Big Man
            # Era; ball movement through guards is more central in guard-favorable
            # eras.
            is_guard = roster.position.isin(["PG", "SG"])
            usage = np.clip(0.16 + 0.03 * roster.base_skill / 2.2 + rng.normal(0, 0.02, n), 0.10, 0.36)
            pts36 = np.clip(9 + 5.5 * roster.base_skill / 2.2 + rng.normal(0, 1.5, n), 3, 34)
            reb36 = np.clip(4 + 5 * big_wt * is_big.astype(float) +
                             1.5 * roster.base_skill / 2.2 + rng.normal(0, 1.2, n), 1.5, 16)
            ast36 = np.clip(2 + 4 * guard_wt * is_guard.astype(float) +
                             1.2 * roster.base_skill / 2.2 + rng.normal(0, 1.0, n), 0.5, 11)
            stl36 = np.clip(0.6 + 0.35 * roster.base_skill / 2.2 + rng.normal(0, 0.3, n), 0.1, 2.6)
            blk36 = np.clip(0.3 + 1.4 * big_wt * is_big.astype(float) + 0.25 * roster.base_skill / 2.2 +
                             rng.normal(0, 0.3, n), 0.0, 3.5)
            tov36 = np.clip(1.2 + 0.15 * usage * 10 + rng.normal(0, 0.4, n), 0.6, 4.5)
            # True Shooting %: blends 2pt/3pt/FT efficiency directly (not derived
            # after the fact), scaled to the real NBA's ~0.50-0.60 range.
            ts_pct = np.clip(
                0.50 + 0.35 * (fg_pct - 0.44) + 0.10 * three_att_rate * (three_pct - 0.34) * 10
                + 0.06 * (ft_pct - 0.75) + 0.02 * roster.base_skill / 2.2 + rng.normal(0, 0.015, n),
                0.42, 0.68,
            )

            roster = roster.assign(
                season=season, year=year, team=team, three_att_rate=three_att_rate,
                fg_pct=fg_pct, three_pct=three_pct, ft_pct=ft_pct, usage_rate=usage,
                pts_per36=pts36, reb_per36=reb36, ast_per36=ast36, stl_per36=stl36,
                blk_per36=blk36, tov_per36=tov36, ts_pct=ts_pct,
            )
            player_season_rows.append(roster)

            # Team-level weighted skill (minutes x availability-weighted).
            weight = roster.minutes_per_game * roster.games_played
            weighted_skill = np.average(effective_rating, weights=weight.clip(lower=1))
            team_skill[team] = weighted_skill
            team_rows_this_year[team] = roster

        # Convert weighted skill into offensive/defensive ratings and point
        # differential, then apply the real Basketball-Reference Pythagorean
        # win-expectation formula -- so team_rating -> net rating -> points
        # for/against -> wins flows the same way it does in the real league,
        # and features.pythagorean_win_pct can later be checked against
        # actual win_pct as a sanity test of the whole chain.
        league_mean_skill = np.mean(list(team_skill.values()))
        team_year_rows = []
        for team in TEAMS:
            rel_skill = team_skill[team] - league_mean_skill
            net_rating = rel_skill * 4.0 + rng.normal(0, 1.5)  # ~ -12..+12 typical NBA range
            pace = np.clip(era_pace(year) + rng.normal(0, 2), 85, 108)
            off_rating = 113.0 + net_rating / 2 + rng.normal(0, 1.0)
            def_rating = off_rating - net_rating
            pts_for = off_rating / 100 * pace
            pts_against = def_rating / 100 * pace

            win_pct = pts_for ** 13.91 / (pts_for ** 13.91 + pts_against ** 13.91)
            win_pct = np.clip(win_pct + rng.normal(0, 0.02), 0.03, 0.97)
            wins = int(round(rng.binomial(82, win_pct)))
            roster = team_rows_this_year[team]
            weight = (roster.minutes_per_game * roster.games_played).clip(lower=1)
            team_year_rows.append({
                "season": season, "year": year, "team": team,
                "conference": "East" if team in EASTERN_CONFERENCE else "West",
                "wins": wins, "losses": 82 - wins, "win_pct": wins / 82,
                "team_rating": team_skill[team], "net_rating": net_rating,
                "off_rating": off_rating, "def_rating": def_rating,
                "pts_for": pts_for, "pts_against": pts_against,
                "avg_three_att_rate": np.average(roster.three_att_rate, weights=weight),
                "avg_fg_pct": np.average(roster.fg_pct, weights=weight),
                "avg_three_pct": np.average(roster.three_pct, weights=weight),
                "avg_ft_pct": np.average(roster.ft_pct, weights=weight),
                "avg_ts_pct": np.average(roster.ts_pct, weights=weight),
                "avg_tov_per36": np.average(roster.tov_per36, weights=weight),
                "pace": pace,
                "roster_continuity": np.mean([
                    1 if pid in prior_rosters.get(team, []) else 0 for pid in roster.player_id
                ]) if year > start_year else np.nan,
                "coach_tenure_years": rng.integers(1, 12),
            })
        team_season_df = pd.DataFrame(team_year_rows)
        team_season_rows.append(team_season_df)

        # -------------------- Playoffs --------------------
        playoff_result_rows.append(
            _simulate_season_playoffs(team_season_df, team_rows_this_year, season, year, rng)
        )

    player_seasons = pd.concat(player_season_rows, ignore_index=True)
    team_seasons = pd.concat(team_season_rows, ignore_index=True)
    playoff_results = pd.concat(playoff_result_rows, ignore_index=True)

    # Attach playoff (per-36) stats for players whose team made the playoffs,
    # using each player's persistent playoff_delta_latent.
    player_seasons = _attach_playoff_player_stats(player_seasons, playoff_results, rng)

    return {"player_seasons": player_seasons, "team_seasons": team_seasons,
            "playoff_results": playoff_results}


def _simulate_season_playoffs(team_season_df: pd.DataFrame, team_rosters: dict[str, pd.DataFrame],
                               season: str, year: int, rng: np.random.Generator) -> pd.DataFrame:
    """Seed top-8 per conference by wins, then simulate the bracket using
    each team's rating adjusted for playoff-delta tendency of its rotation.
    """
    rows = []
    ratings_by_conf: dict[str, dict[int, float]] = {}
    seed_team_map: dict[str, dict[int, str]] = {}

    for conf in ("East", "West"):
        conf_teams = team_season_df[team_season_df.conference == conf].sort_values(
            "wins", ascending=False
        ).reset_index(drop=True)
        seeds = {}
        seed_map = {}
        for i, row in conf_teams.iterrows():
            seed = i + 1
            roster = team_rosters[row.team]
            weight = (roster.minutes_per_game * roster.games_played).clip(lower=1)
            # Ratings for bracket simulation are net_rating (real point-differential
            # scale), nudged by the team's rotation's playoff-delta tendency
            # (typically a modest +/-1-3 point swing, not a dominant factor).
            playoff_adjust = np.average(roster.playoff_delta_latent, weights=weight) * 3.0
            seeds[seed] = row.net_rating + playoff_adjust if seed <= 8 else None
            seed_map[seed] = row.team
            rows.append({
                "season": season, "year": year, "team": row.team, "conference": conf,
                "seed": seed, "made_playoffs": seed <= 8, "rounds_won": 0, "champion": False,
            })
        ratings_by_conf[conf] = {s: r for s, r in seeds.items() if s <= 8}
        seed_team_map[conf] = seed_map

    result_df = pd.DataFrame(rows)

    def _record_round(conf, seed, rounds_won):
        team = seed_team_map[conf][seed]
        mask = (result_df.team == team) & (result_df.season == season)
        result_df.loc[mask, "rounds_won"] = max(result_df.loc[mask, "rounds_won"].iloc[0], rounds_won)

    from src.simulate import simulate_conference_bracket, simulate_series

    conf_champ = {}
    for conf in ("East", "West"):
        bracket = simulate_conference_bracket(ratings_by_conf[conf], rng)
        for s in bracket["round_of_16_winners"]:
            _record_round(conf, s, 1)
        for s in bracket["conf_semi_winners"]:
            _record_round(conf, s, 2)
        _record_round(conf, bracket["conf_champion_seed"], 3)
        conf_champ[conf] = bracket["conf_champion_seed"]

    e_rating = ratings_by_conf["East"][conf_champ["East"]]
    w_rating = ratings_by_conf["West"][conf_champ["West"]]
    east_is_higher = e_rating >= w_rating
    winner = simulate_series(e_rating, w_rating, higher_seed_is_a=east_is_higher, rng=rng)
    finals_loser_conf = "West" if (winner == "A") == east_is_higher else "East"
    finals_winner_conf = "East" if finals_loser_conf == "West" else "West"

    _record_round(finals_winner_conf, conf_champ[finals_winner_conf], 4)
    champ_team = seed_team_map[finals_winner_conf][conf_champ[finals_winner_conf]]
    result_df.loc[result_df.team == champ_team, "champion"] = True

    return result_df


def _attach_playoff_player_stats(player_seasons: pd.DataFrame, playoff_results: pd.DataFrame,
                                  rng: np.random.Generator) -> pd.DataFrame:
    made_playoffs = playoff_results[playoff_results.made_playoffs][["season", "team", "rounds_won"]]
    merged = player_seasons.merge(made_playoffs, on=["season", "team"], how="left")
    in_playoffs = merged.rounds_won.notna()

    n = in_playoffs.sum()
    noise_scale = 0.6
    delta = merged.loc[in_playoffs, "playoff_delta_latent"]
    merged.loc[in_playoffs, "playoff_pts_per36"] = (
        merged.loc[in_playoffs, "pts_per36"] + delta * 1.8 + rng.normal(0, noise_scale, n)
    ).clip(lower=0)
    merged.loc[in_playoffs, "playoff_ts_pct"] = np.clip(
        merged.loc[in_playoffs, "ts_pct"] + delta * 0.02 + rng.normal(0, 0.02, n), 0.35, 0.72
    )
    playoff_games_available = np.clip(4 + merged.loc[in_playoffs, "rounds_won"] * 5, 4, 24)
    injury_dip = rng.binomial(playoff_games_available.astype(int), merged.loc[in_playoffs, "injury_proneness"] * 0.5)
    merged.loc[in_playoffs, "playoff_games_played"] = (playoff_games_available - injury_dip).clip(lower=0)

    return merged


# --------------------------------------------------------------------------
# 3. Unified loader
# --------------------------------------------------------------------------

def load_league(start_year: int = START_SEASON_YEAR, end_year: int = END_SEASON_YEAR,
                 prefer_real: bool = True, seed: int = RANDOM_SEED) -> dict[str, pd.DataFrame]:
    """Try real nba_api data per season; fall back to the synthetic league
    generator for any season (or entirely) when live data isn't reachable.
    """
    if prefer_real:
        any_real = False
        for year in range(start_year, end_year + 1):
            if fetch_real_season(year) is not None:
                any_real = True
        if any_real:
            warnings.warn(
                "Partial real-data support detected but full real pipeline "
                "(rosters/injuries/playoff results) is not implemented; "
                "using synthetic league for consistent modeling."
            )
    return generate_synthetic_league(start_year, end_year, seed=seed)
